#!/bin/bash

CONFIG_SRC_DIR=$HOME/Documents/configuration/src
WORKSTATION_CONFIG_DIR=$HOME/Documents/configuration/workstation
MAIL_RECIPE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

brew install alot isync msmtp

if [ ! -d $HOME/mail/work ]; then
    mkdir -p $HOME/mail/work
fi

source $WORKSTATION_CONFIG_DIR/mail-recipe
if [ ! -d $CONFIG_SRC_DIR/.msmtp ]; then
    git clone $MSMTP_REPO_URL $CONFIG_SRC_DIR/.msmtp
    ln -s -f $CONFIG_SRC_DIR/.msmtp/msmtprc $HOME/.msmtprc
fi

if [ ! -d $CONFIG_SRC_DIR/.mbsync ]; then
    git clone $MBSYNC_REPO_URL $CONFIG_SRC_DIR/.mbsync
    ln -s -f $CONFIG_SRC_DIR/.mbsync/mbsyncrc $HOME/.mbsyncrc
fi

sudo cp --update $MAIL_RECIPE_DIR/files/sync-mail /usr/local/bin
sudo chmod +x /usr/local/bin/sync-mail
