#!/bin/bash

CONFIG_SRC_DIR=$HOME/Documents/configuration/src
WORKSTATION_CONFIG_DIR=$HOME/Documents/configuration/workstation
MAIL_RECIPE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

shef brew alot
shef brew isync
shef brew msmtp
shef brew notmuch

if [ ! -d $HOME/mail/work ]; then
    mkdir -p $HOME/mail/work
fi

# TODO prompt user to create the mail-recipe file
source $WORKSTATION_CONFIG_DIR/mail-recipe
if [ ! -d $CONFIG_SRC_DIR/.msmtp ]; then
    git clone $MSMTP_REPO_URL $CONFIG_SRC_DIR/.msmtp
    ln -s -f $CONFIG_SRC_DIR/.msmtp/msmtprc $HOME/.msmtprc
fi
cd $CONFIG_SRC_DIR/.msmtp
git pull
cd -

if [ ! -d $CONFIG_SRC_DIR/.mbsync ]; then
    git clone $MBSYNC_REPO_URL $CONFIG_SRC_DIR/.mbsync
    ln -s -f $CONFIG_SRC_DIR/.mbsync/mbsyncrc $HOME/.mbsyncrc
fi
cd $CONFIG_SRC_DIR/.mbsync
git pull
cd -

if [ ! -d $CONFIG_SRC_DIR/.notmuch ]; then
    git clone $NOTMUCH_REPO_URL $CONFIG_SRC_DIR/.notmuch
    ln -s -f $CONFIG_SRC_DIR/.notmuch/notmuch-config $HOME/.notmuch-config
fi
cd $CONFIG_SRC_DIR/.notmuch
git pull
cd -

if [ ! -d $CONFIG_SRC_DIR/.alot ]; then
    git clone $ALOT_REPO_URL $CONFIG_SRC_DIR/.alot
    mkdir -p $HOME/.config/alot
fi

cd $CONFIG_SRC_DIR/.alot
git pull

ln -s -f $CONFIG_SRC_DIR/.alot/config $HOME/.config/alot/config
ln -s -f $CONFIG_SRC_DIR/.alot/hooks.py $HOME/.config/alot/hooks.py
ln -s -f $CONFIG_SRC_DIR/.alot/mailcap $HOME/.mailcap

cd -

cp /home/linuxbrew/.linuxbrew/share/alot/alot.desktop $HOME/.local/share/applications

FIND_MAILTO=$(grep -nri "mailto" $HOME/.local/share/applications/mimeapps.list)
if [ $? -eq 1 ]; then
    echo "x-scheme-handler/mailto=alot.desktop" >> $HOME/.local/share/applications/mimeapps.list
fi

sudo cp --update $MAIL_RECIPE_DIR/files/sync-mail /usr/local/bin
sudo chmod +x /usr/local/bin/sync-mail

sudo cp --update $MAIL_RECIPE_DIR/files/zmail /usr/local/bin
sudo chmod +x /usr/local/bin/zmail

cp --update $MAIL_RECIPE_DIR/files/zmail.desktop $HOME/.local/share/applications
cp --update $MAIL_RECIPE_DIR/files/zmail.png $HOME/.local/share/icons

if [ ! -d $HOME/.local/configuration/mail ]; then
    mkdir -p $HOME/.local/configuration/mail
fi

cp --update $MAIL_RECIPE_DIR/files/tmux.conf $HOME/.local/configuration/mail

cp --update $MAIL_RECIPE_DIR/files/zmail.yml $HOME/.config/tmuxinator

(crontab -l ; echo "*/5 * * * * sync-mail") 2>&1 | grep -v "no crontab" | sort | uniq | crontab -

sudo cp --update $MAIL_RECIPE_DIR/files/prompt-for-gpg-key /usr/local/bin

cp --update $MAIL_RECIPE_DIR/files/prompt-for-gpg-key.desktop $HOME/.local/share/applications/prompt-for-gpg-key.desktop

pip3 install urlscan
