#!/bin/bash

export PASSWORD_STORE_DIR=/home/leonard/.password-store
export PATH=/home/linuxbrew/.linuxbrew/bin:$PATH

if ! mbsync  --config /home/leonard/.mbsyncrc --quiet work; then
    echo "$(date +'%d/%m/%Y %H:%M:%S'): ✗ Sync failed"
else
    echo "$(date +'%d/%m/%Y %H:%M:%S'): ✓ Sync succeeded"
    if ! notmuch new > /dev/null 2>&1; then
      echo "$(date +'%d/%m/%Y %H:%M:%S'): ✗ Notmuch indexation failed"
    else
      echo "$(date +'%d/%m/%Y %H:%M:%S'): ✓ Notmuch indexation succeeded"
    fi
fi

